### ISSUE TITLE
Replace `$ARCH` with `$PORT_ARCH`?

### ISSUE THREAD

**Issue by simonvanderveldt** [mer-hybris/droid-hal-device#132]
HADK 1.1.2 says in chapter 4.1/page 11:
```
# ARCH conflicts with kernel build
export PORT_ARCH="armv7hl"
```

But the helper scripts in this repo make use of the `$ARCH` env var.
Shouldn't the helper scripts in this repo be updated to use the same variable?

**Comment by mlehtima** [comment]
That might be a good idea as that would make building for other than armv7hl easier, currently $ARCH defaults to armv7hl in helpers/util.sh if unset. I can make a patch if needed.

**Comment by simonvanderveldt** [comment]
@mlehtima thanks for the hint, `helpers/util.sh` does indeed set a default, but it actually didn't work for me, because in my profile I already set an `ARCH` env var to the value of my host OS's arch, so it used that and thus didn't work :)

I guess using `PORT_ARCH` does indeed make more sense.
Is it just a case of replacing the env var in all files in `./helper`? In that case I can create a PR as well.

**Comment by mlehtima** [comment]
@simonvanderveldt Replacing all instances of `$ARCH` with `$PORT_ARCH` in those files should be enough.
