### ISSUE TITLE
makefstab should skip swap partitions

### ISSUE THREAD

**Issue by piggz** [mer-hybris/droid-hal-device#163]
makefstab creates invalid .mount files when it encounters a swap line in an fstab.

systemd handles swaps in .swap units, not .mount units.  Example, on falcon, a none.mount file is created that tries to mount /dev/block/zram0, but cannot.

**Comment by piggz** [comment]
ah, i see i can specify makefstab_skip_entries

**Comment by mlehtima** [comment]
But wouldn't the proper solution be to add 'none' to the skipped list?

**Comment by piggz** [comment]
It may be!

**Comment by mlehtima** [comment]
To be fixed in https://github.com/mer-hybris/droid-hal-device/pull/173

**Comment by Thaodan** [comment]
Can we close this as #173 is merged?
