### ISSUE TITLE
Strange behavior of "droidmedia-localbuild.spec" when try to build droidmedia

### ISSUE THREAD

**Issue by AirDeeEx** [mer-hybris/droid-hal-device#332]
Build failed after another droid-hal sync. Port tree was totally reassembled for clearer results, but the error remained.

Log last parts is:  
``` 
Processing files: droidmedia-0.20220929.0-1.armv7hl
error: File not found: /home/build/hadk/hybris/mw/droidmedia-localbuild/installroot/usr/libexec/droid-hybris/system/etc/init/hybris_extras.rc
error: More than one file on a line: /usr/libexec/droid-hybris/system/etc/init/servicemanager.rc


RPM build errors:
    File not found: /home/build/hadk/hybris/mw/droidmedia-localbuild/installroot/usr/libexec/droid-hybris/system/etc/init/hybris_extras.rc
    More than one file on a line: /usr/libexec/droid-hybris/system/etc/init/servicemanager.rc
```

After debugging it was found that the file "droidmedia-localbuild/file.list" is incorrect:
```
/usr/libexec/droid-hybris/system/lib/libdroidmedia.so
/usr/libexec/droid-hybris/system/lib/libminisf.so
/usr/libexec/droid-hybris/system/etc/init/hybris_extras.rc /usr/libexec/droid-hybris/system/etc/init/servicemanager.rc
```

As far as I understand, it should be similar to:
```
/usr/libexec/droid-hybris/system/lib/libdroidmedia.so
/usr/libexec/droid-hybris/system/lib/libminisf.so
/usr/libexec/droid-hybris/system/etc/init/minimediaservice.rc
/usr/libexec/droid-hybris/system/etc/init/minisfservice.rc
```
After several experiments, there was definitely a strange behavior of "match all" wildcard, and the explicit assignment seams to fix that.
Example: 
```
if [ -d $RPM_BUILD_ROOT/%{_libexecdir}/droid-hybris/system/etc/init ]; then
echo %{_libexecdir}/droid-hybris/system/etc/init/minimediaservice.rc >> ${LIBDMSOLOC}
echo %{_libexecdir}/droid-hybris/system/etc/init/minisfservice.rc >> ${LIBDMSOLOC}
fi
```
So, the main question is: unexpected behavior (maybe related to https://github.com/mer-hybris/droid-hal-device/commit/0d7298d8e662cc87c45aecb2a8fba9986e93d0a3) or build environment problems?

(A translator was used, so I hope you can understand that.)

**Comment by piggz** [comment]
I have also had this issue

**Comment by mlehtima** [comment]
This pull request should fix the issue https://github.com/mer-hybris/droid-hal-device/pull/333

**Comment by AirDeeEx** [comment]
I can confirm #333 fix my problem, thanks
